language: node_js
node_js: 6.1.0
sudo: false
cache:
  directories:
  - node_modules
before_script:
- npm install -g gulp
script:
- npm run build
after_success:
- |
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
    git config credential.helper "store --file=.git/credentials"
    echo "https://${GH_TOKEN}:@github.com" > .git/credentials
    git config --global user.name "Grommet Community Bot"
    git config --global user.email "eric.soderberg@hpe.com"
    gulp release:stable
  fi
env:
  global:
    secure: YUmfNkPrD0t+Aup78HF4WDzSM5B028XypUdiyP01Q9aLMytseOfJKKagZQrONGkTfikA1gK0OH9itd1TXU8vPnrjHRFrUYOiSqiIAMvkfI+mGbBceUKHR2XZt75fr4yF7hTIx0sj+qwaHXB/vgehXC0Yl8+OLrnA5h7PbHdXtZUQcCsDBDKCI4yGJ8Gd+7e5Eg7wTMKDSWzbgklQRH6TcaqdvNzkXIM8Ape4rPxHkRqmWwo9cN6YSBBu13YPz3XqP4Ynhonoj1D0dsxq8ldAG4OdQXoSHDyG5RQmi6ifH9qwPCNaAchCFyFaOZCLE8k6AtNZ8kzLsSqknSDoqIJeROLWExp6pwbhiZRhYofzuRa4HgbQebfSB7DkLeDBOmK48iLCSnh27DD7Jvg43gwnyCFJi5VFjbpK6lHdVhaE4rjPra/tzeghzAIcFwFNfjoOj8NBXwMd2khc+yLGlzBNcSsCn8KiYD5U90ZQwl/x8utVNCUYVI5sAbVDmFlJleiuKfwwmqvXHjfuTY1VUi0N/QfT6QIFe+DhoFlc7Pspv1IHb0kr08q8oBLSCXuBjHRN8o1RyEuJ+KLz9XZpOriXUBvXeAQQ9vpvC3sKgvNu+NU3gOjGKpk4z5eXC5eQsK2qXb881O7nR+VdYSZYy13+dFabd5k7itWiaqIVq+zul/o=
